Models/ServiceRequest.cs
using System;
using System.Collections.Generic;

namespace FYPHomecare.Models
{
    public partial class ServiceRequest
    {
        public int ServiceRequestId { get; set; }
        public string Description { get; set; }
        public DateTime RequestDate { get; set; }
        public DateTime AppointmentDatetime { get; set; }
        public string Status { get; set; }
        public int PatientId { get; set; }

        public virtual Patient Patient { get; set; }
    }
}

Controllers/QuoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FYPHomecare.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FYPHomecare.Controllers
{
    public class QuoteController : Controller
    {
        private AppDbContext _dbContext;

        public QuoteController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            DbSet<Quote> dbs = _dbContext.Quote;
            List<Quote> model = dbs.ToList();

            return View(model);
        }

        public IActionResult Create()
        {
            DbSet<ServiceProvider> dbs = _dbContext.ServiceProvider;
            var lstPokes =
                dbs.ToList<ServiceProvider>()
                   .OrderBy(p => p.ServiceProviderId)
                   .Select(
                       p =>
                       {
                           dynamic d = new ExpandoObject();
                           d.value = p.ServiceProviderId;
                           d.text = p.Name;
                           return d;
                       }
                   )
                   .ToList<dynamic>();
            ViewData["pokes"] = lstPokes;

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Quote newquote)
        {
            ServiceRequest sq = (ServiceRequest)TempData["Info"];
            DbSet<ServiceProvider> dbS = _dbContext.ServiceProvider;
            DbSet<Patient> patient = _dbContext.Patient;
            DbSet<Users> user = _dbContext.Users;
            Quote model = newquote;

            if (ModelState.IsValid)
            {
                
                DbSet<Quote> dbs = _dbContext.Quote;
                var serviceproviderid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                ServiceProvider sp = dbS.Where(s => s.ServiceProviderId == Int32.Parse(serviceproviderid)).FirstOrDefault();
                newquote.ServiceProviderId = sp.ServiceProviderId;
                
                Patient test = patient.Where(s => s.PatientId == sq.PatientId).FirstOrDefault();
                Users usertest = user.Where(s => s.UsersId == test.UsersId).FirstOrDefault();

                //DbSet<ServiceRequest> servicerequest = _dbContext.ServiceRequest;
                newquote.UsersId = usertest.UsersId;
        
                dbs.Add(newquote);
                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "New Quote Created!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }


    }
}

Controllers/ServiceRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FYPHomecare.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FYPHomecare.Controllers
{
    public class ServiceRequestController : Controller
    {
        private AppDbContext _dbContext;


        public ServiceRequestController(AppDbContext dbContext)

        {

            _dbContext = dbContext;

        }


        public IActionResult Index()
        {
            

            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            DbSet<Users> userdata = _dbContext.Users;
            Users user = userdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();

            DbSet<Patient> dbS = _dbContext.Patient;
            Patient patient = dbS.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();

            DbSet<ServiceRequest> dbs = _dbContext.ServiceRequest;
            List<ServiceRequest> model = null;

            if (User.IsInRole("ServiceProvider"))
            {
                model = dbs.ToList();
                //return RedirectToAction("Create", "Quote");
            }
            else
            {
                model = dbs.Where(m => m.PatientId == patient.PatientId && patient.UsersId == user.UsersId).ToList();
            }

            return View(model);

        }

        public IActionResult Create()
        {
            DbSet<Patient> dbs = _dbContext.Patient;
            var lstPokes =
                dbs.ToList<Patient>()
                   .OrderBy(p => p.PatientId)
                   .Select(
                       p =>
                       {
                           dynamic d = new ExpandoObject();
                           d.value = p.PatientId;
                           d.text = p.Name;
                           return d;
                       }
                   )
                   .ToList<dynamic>();
            ViewData["pokes"] = lstPokes;

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(ServiceRequest sq)
        {
            DbSet<Users> userdata = _dbContext.Users;
            DbSet<Patient> patientdata = _dbContext.Patient;
            ServiceRequest model = sq;
            if (ModelState.IsValid)
            {
                DbSet<ServiceRequest> dbs = _dbContext.ServiceRequest;
                var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                Users user = userdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
                Patient patient = patientdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();

                sq.PatientId = patient.PatientId;

                dbs.Add(sq);
                if (_dbContext.SaveChanges() == 1)
                {
                    TempData["Msg"] = "New Service Request added!";
                    //TempData["Test"] = sq;
                }
                    
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            DbSet<Users> userdata = _dbContext.Users;
            DbSet<Patient> patientdata = _dbContext.Patient;
            DbSet<ServiceRequest> dbs = _dbContext.ServiceRequest;
            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            Users user = userdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
            Patient patient = patientdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();

            ServiceRequest tOrder = dbs.Where(mo => mo.PatientId == patient.PatientId && patient.UsersId == user.UsersId).FirstOrDefault();

            tOrder.ServiceRequestId = id;
            if (tOrder != null)
            {
                
                var lstPokes =
                    patientdata.ToList<Patient>()
                       .OrderBy(p => p.PatientId)
                       .Select(
                           p =>
                           {
                               dynamic d = new ExpandoObject();
                               d.value = p.PatientId;
                               d.text = p.Name;
                               return d;
                           }
                       )
                       .ToList<dynamic>();
                ViewData["pokes"] = lstPokes;

                return View();
            }
            else
            {
                TempData["Msg"] = "Service Request Not found!";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(ServiceRequest sq)
        {
            DbSet<Patient> dbS = _dbContext.Patient;
            DbSet<Users> userdata = _dbContext.Users;
            if (ModelState.IsValid)
            {
                DbSet<ServiceRequest> dbs = _dbContext.ServiceRequest;

                var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                Users user = userdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
                Patient patient = dbS.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
                ServiceRequest tOrder = dbs.Where(mo => mo.PatientId == patient.PatientId && patient.UsersId == user.UsersId).FirstOrDefault();

                sq.ServiceRequestId = tOrder.ServiceRequestId;

                if (tOrder != null)
                {
                    tOrder.Description = sq.Description;
                    tOrder.RequestDate = sq.RequestDate;
                    tOrder.AppointmentDatetime = sq.AppointmentDatetime;
                    tOrder.Status = sq.Status;


                    if (_dbContext.SaveChanges() == 1)
                        TempData["Msg"] = "Service Request updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }
                else
                {
                    TempData["Msg"] = "Service Request not found yet!";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

    }
}

Views/ServiceRequest/Create.cshtml
@model ServiceRequest
@{
    ViewBag.Title = "New Service Request";

    var pokes = ViewData["pokes"] as List<dynamic>;
    pokes.Insert(0, new { value = "", text = "-- SELECT --" });
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-6">
        <form asp-controller="ServiceRequest" asp-action="Create" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">
                <div class="form-group">
                    <label asp-for="Description" class="col-sm-4 control-label">Description</label>
                    <div class="col-sm-6">
                        <input id="txtName" asp-for="Description" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" asp-for="RequestDate">Request Date : </label>
                    <div class="col-sm-6">
                        <div class='input-group date' id='BsDateTimePicker'>
                            <input placeholder="YYYY-MM-DD" class="form-control" asp-for="RequestDate" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" asp-for="AppointmentDatetime">AppointmentDatetime : </label>
                    <div class="col-sm-6">
                        <div class='input-group date' id='BsDatePicker'>
                            <input placeholder="YYYY-MM-DD" class="form-control" asp-for="AppointmentDatetime" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Status" class="col-sm-2 control-label"></label>
                    <div class="col-sm-7">
                        <input type="radio" asp-for="Status" value="New" checked="checked" /> New
                        <input type="radio" asp-for="Status" value="Pending" /> Pending
                        <input type="radio" asp-for="Status" value="Completed" /> Completed
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Views/ServiceRequest/Index.cshtml
@model List<ServiceRequest>

@{
    ViewBag.Title = "Service Request";
}


<h2>Service Request</h2>

<span style="color:red">@TempData["Msg"]</span><br />
<p>
    <a asp-controller="ServiceRequest" asp-action="Create">Create New</a>
</p>

<table class="table">
    <tr>
        <th>Request ID</th>
        <th>Description</th>
        <th>Appointment</th>
        <th>Request Date</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.ServiceRequestId
            </td>
            <td>
                @item.Description
            </td>
            <td>
                @item.AppointmentDatetime 
            </td>
            <td>
                @item.RequestDate
            </td>
            <td>
                @if (User.IsInRole("User"))
                {
                <a asp-controller="ServiceRequest" asp-action="Update">Update</a>
                <a asp-action="Delete" asp-route-id="@item.PatientId" onclick="return ConfirmDelete()">Delete</a>
                }
                else if (User.IsInRole("ServiceProvider"))
                {
                    <a asp-controller="Quote" asp-action="Create">Send Quotion</a>
                }
            </td>
        </tr>
    }
</table>

Views/ServiceRequest/Update.cshtml
@model ServiceRequest


@{
    ViewBag.Title = "Update Service Request";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-6">
        <form asp-controller="ServiceRequest" asp-action="Update" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">

                <div class="form-group">
                    <label asp-for="Description" class="col-sm-4 control-label">Description</label>
                    <div class="col-sm-6">
                        <input id="txtName" asp-for="Description" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" asp-for="RequestDate">Request Date : </label>
                    <div class="col-sm-6">
                        <div class='input-group date' id='BsDateTimePicker'>
                            <input placeholder="YYYY-MM-DD" class="form-control" asp-for="RequestDate" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" asp-for="AppointmentDatetime">AppointmentDatetime : </label>
                    <div class="col-sm-6">
                        <div class='input-group date' id='BsDatePicker'>
                            <input placeholder="YYYY-MM-DD" class="form-control" asp-for="AppointmentDatetime" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Status" class="col-sm-2 control-label"></label>
                    <div class="col-sm-7">
                        <input type="radio" asp-for="Status" value="New" checked="checked" /> New
                        <input type="radio" asp-for="Status" value="Pending" /> Pending
                        <input type="radio" asp-for="Status" value="Completed" /> Completed
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>