Models/Patient.cs
using System;
using System.Collections.Generic;

namespace FYPHomecare.Models
{
    public partial class Patient
    {
        public Patient()
        {
            ServiceRequest = new HashSet<ServiceRequest>();
        }

        public int PatientId { get; set; }
        public string Name { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Nric { get; set; }
        public string MedicalHistory { get; set; }
        public decimal AnnualIncome { get; set; }
        public int UsersId { get; set; }
        public string Address { get; set; }
        public string RelationshipToUser { get; set; }
        public int Postalcode { get; set; }
        public int Phone { get; set; }
        public string Gender { get; set; }

        public virtual ICollection<ServiceRequest> ServiceRequest { get; set; }
    }
}

Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FYPHomecare.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FYPHomecare.Controllers
{
    public class PatientController : Controller
    {
        private AppDbContext _dbContext;


        public PatientController(AppDbContext dbContext)

        {

            _dbContext = dbContext;

        }
        private Users curUser()
        {
            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            DbSet<Users> dbs = _dbContext.Users;
            Users user = dbs.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
            return user;
        }

        public IActionResult Index()
        {
            DbSet<Patient> dbs = _dbContext.Patient;

            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            DbSet<Users> dbS = _dbContext.Users;
            Users user = dbS.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
            List<Patient> model = null;

            model = dbs.Where(m => m.UsersId == user.UsersId).ToList();
            

            return View(model);
        }





        public IActionResult Create()
        {
            DbSet<Users> dbs = _dbContext.Users;
            var lstPokes =
                dbs.ToList<Users>()
                   .OrderBy(p => p.UsersId)
                   .Select(
                       p =>
                       {
                           dynamic d = new ExpandoObject();
                           d.value = p.UsersId;
                           d.text = p.Name;
                           return d;
                       }
                   )
                   .ToList<dynamic>();
            ViewData["pokes"] = lstPokes;

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Patient newpatient)
        {
            DbSet<Users> dbS = _dbContext.Users;
            Patient model = newpatient;
            if (ModelState.IsValid)
            {
                DbSet<Patient> dbs = _dbContext.Patient;
                var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                Users user = dbS.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
                newpatient.UsersId = user.UsersId;

                dbs.Add(newpatient);
                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "New Patient added!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            DbSet<Patient> dbs = _dbContext.Patient;
            Patient tOrder = dbs.Where(mo => mo.PatientId == id).FirstOrDefault();

            if (tOrder != null)
            {
                
                DbSet<Users> dbS = _dbContext.Users;
                var lstPokes =
                        dbS.ToList<Users>()
                                .OrderBy(p => p.Name)
                                .Select(
                                    p =>
                                    {
                                        dynamic d = new ExpandoObject();
                                        d.value = p.UsersId;
                                        d.text = p.Name;
                                        return d;
                                    }
                                )
                                .ToList<dynamic>();
                ViewData["pokes"] = lstPokes;

                return View(tOrder);
            }
            else
            {
                TempData["Msg"] = "Patient not found!";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(Patient patient)
        {
            DbSet<Users> dbS = _dbContext.Users;
            if (ModelState.IsValid)
            {
                DbSet<Patient> dbs = _dbContext.Patient;
                Patient tOrder = dbs.Where(mo => mo.PatientId == patient.PatientId)
                                     .FirstOrDefault();

                var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                Users user = dbS.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
                patient.UsersId = user.UsersId;
                if (tOrder != null)
                {
                    tOrder.Name = patient.Name;
                    tOrder.DateOfBirth = patient.DateOfBirth;
                    tOrder.Nric = patient.Nric;
                    tOrder.MedicalHistory = patient.MedicalHistory;
                    tOrder.AnnualIncome = patient.AnnualIncome;
                    tOrder.Address = patient.Address;
                    tOrder.RelationshipToUser = patient.RelationshipToUser;
                    tOrder.Postalcode = patient.Postalcode;
                    tOrder.Phone = patient.Phone;
                    tOrder.Gender = patient.Gender;


                    if (_dbContext.SaveChanges() == 1)
                        TempData["Msg"] = "Patient Information updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }
                else
                {
                    TempData["Msg"] = "Patient not found yet!";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            DbSet<Patient> dbs = _dbContext.Patient;

            Patient tOrder = dbs.Where(mo => mo.PatientId == id).FirstOrDefault();


            //MugOrder tOrder = null; // this line needs to be modified to achieve Task 2-2

            if (tOrder != null)
            {
                // TODO P10 Task 2-3 Use Remove method to remove the found MugOrder object from DbSet
                dbs.Remove(tOrder);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "Patient Information deleted!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Patient Information not found!";
            }
            return RedirectToAction("Index");
        }

    }
}

Controllers/ServiceRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FYPHomecare.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FYPHomecare.Controllers
{
    public class ServiceRequestController : Controller
    {
        private AppDbContext _dbContext;


        public ServiceRequestController(AppDbContext dbContext)

        {

            _dbContext = dbContext;

        }


        public IActionResult Index()
        {
            

            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            DbSet<Users> userdata = _dbContext.Users;
            Users user = userdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();

            DbSet<Patient> dbS = _dbContext.Patient;
            Patient patient = dbS.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();

            DbSet<ServiceRequest> dbs = _dbContext.ServiceRequest;
            List<ServiceRequest> model = null;

            if (User.IsInRole("ServiceProvider"))
            {
                model = dbs.ToList();
                //return RedirectToAction("Create", "Quote");
            }
            else
            {
                model = dbs.Where(m => m.PatientId == patient.PatientId && patient.UsersId == user.UsersId).ToList();
            }

            return View(model);

        }

        public IActionResult Create()
        {
            DbSet<Patient> dbs = _dbContext.Patient;
            var lstPokes =
                dbs.ToList<Patient>()
                   .OrderBy(p => p.PatientId)
                   .Select(
                       p =>
                       {
                           dynamic d = new ExpandoObject();
                           d.value = p.PatientId;
                           d.text = p.Name;
                           return d;
                       }
                   )
                   .ToList<dynamic>();
            ViewData["pokes"] = lstPokes;

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(ServiceRequest sq)
        {
            DbSet<Users> userdata = _dbContext.Users;
            DbSet<Patient> patientdata = _dbContext.Patient;
            ServiceRequest model = sq;
            if (ModelState.IsValid)
            {
                DbSet<ServiceRequest> dbs = _dbContext.ServiceRequest;
                var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                Users user = userdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
                Patient patient = patientdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();

                sq.PatientId = patient.PatientId;

                dbs.Add(sq);
                if (_dbContext.SaveChanges() == 1)
                {
                    TempData["Msg"] = "New Service Request added!";
                    //TempData["Test"] = sq;
                }
                    
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            DbSet<Users> userdata = _dbContext.Users;
            DbSet<Patient> patientdata = _dbContext.Patient;
            DbSet<ServiceRequest> dbs = _dbContext.ServiceRequest;
            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            Users user = userdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
            Patient patient = patientdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();

            ServiceRequest tOrder = dbs.Where(mo => mo.PatientId == patient.PatientId && patient.UsersId == user.UsersId).FirstOrDefault();

            tOrder.ServiceRequestId = id;
            if (tOrder != null)
            {
                
                var lstPokes =
                    patientdata.ToList<Patient>()
                       .OrderBy(p => p.PatientId)
                       .Select(
                           p =>
                           {
                               dynamic d = new ExpandoObject();
                               d.value = p.PatientId;
                               d.text = p.Name;
                               return d;
                           }
                       )
                       .ToList<dynamic>();
                ViewData["pokes"] = lstPokes;

                return View();
            }
            else
            {
                TempData["Msg"] = "Service Request Not found!";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(ServiceRequest sq)
        {
            DbSet<Patient> dbS = _dbContext.Patient;
            DbSet<Users> userdata = _dbContext.Users;
            if (ModelState.IsValid)
            {
                DbSet<ServiceRequest> dbs = _dbContext.ServiceRequest;

                var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                Users user = userdata.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
                Patient patient = dbS.Where(s => s.UsersId == Int32.Parse(userid)).FirstOrDefault();
                ServiceRequest tOrder = dbs.Where(mo => mo.PatientId == patient.PatientId && patient.UsersId == user.UsersId).FirstOrDefault();

                sq.ServiceRequestId = tOrder.ServiceRequestId;

                if (tOrder != null)
                {
                    tOrder.Description = sq.Description;
                    tOrder.RequestDate = sq.RequestDate;
                    tOrder.AppointmentDatetime = sq.AppointmentDatetime;
                    tOrder.Status = sq.Status;


                    if (_dbContext.SaveChanges() == 1)
                        TempData["Msg"] = "Service Request updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }
                else
                {
                    TempData["Msg"] = "Service Request not found yet!";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Patient/Create.cshtml
@model Patient
@{
    ViewBag.Title = "New Patient";

    var pokes = ViewData["pokes"] as List<dynamic>;
    pokes.Insert(0, new { value = "", text = "-- SELECT --" });
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-6">
        <form asp-controller="Patient" asp-action="Create" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">
                <div class="form-group">
                    <label asp-for="Name" class="col-sm-4 control-label">Name</label>
                    <div class="col-sm-6">
                        <input id="txtName" asp-for="Name" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" asp-for="DateOfBirth">Date Of Birth : </label>
                    <div class="col-sm-4">
                        <div class='input-group date' id='BsDateTimePicker'>
                            <input placeholder="YYYY-MM-DD" class="form-control" asp-for="DateOfBirth" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Nric" class="col-sm-4 control-label">Nric</label>
                    <div class="col-sm-6">
                        <input id="txtName" asp-for="Nric" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="Nric" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3" asp-for="MedicalHistory">Medical History (Max: 200 words) : </label>
                    <div class="col-sm-5">
                        <input type="text" height="7" asp-for="MedicalHistory" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="MedicalHistory" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="AnnualIncome" class="col-sm-2 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="AnnualIncome" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3" asp-for="Address">Address : </label>
                    <div class="col-sm-5">
                        <input type="text" height="7" asp-for="Address" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="RelationshipToUser" class="col-sm-4 control-label">Relationship :</label>
                    <div class="col-sm-6">
                        <input id="txtName" asp-for="RelationshipToUser" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="RelationshipToUser" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Postalcode" class="col-sm-2 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Postalcode" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="col-sm-2 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Phone" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Gender" class="col-sm-2 control-label"></label>
                    <div class="col-sm-7">
                        <input type="radio" asp-for="Gender" value="M" checked="checked" /> M
                        <input type="radio" asp-for="Gender" value="F" /> F
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Views/Patient/Index.cshtml
@model List<Patient>

@{
    ViewBag.Title = "Patient";
}


<h2>Patient</h2>

<span style="color:red">@TempData["Msg"]</span><br />
<p>
    <a asp-controller="Patient" asp-action="Create">Create New</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Medical History</th>
        <th>Date Of Birth</th>
        <th>Phone</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                <a asp-action="Update" asp-route-id="@item.PatientId">@item.MedicalHistory</a>
            </td>
            <td>
                @item.DateOfBirth
            </td>
            <td>
                @item.Phone
            </td>
            <td>
                <a asp-controller="ServiceRequest" asp-action="Create">Request For Service</a>
                <a asp-action="Delete" asp-route-id="@item.PatientId" onclick="return ConfirmDelete()">Delete</a>
            </td>
        </tr>
                }
</table>

Views/Patient/Update.cshtml
@model Patient

@{
    ViewBag.Title = "Update Patient";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-6">
        <form asp-controller="Patient" asp-action="Update" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">
                <div class="form-group">
                    <label asp-for="PatientId" class="col-sm-2 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="PatientId" readonly="readonly" />
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Name" class="col-sm-4 control-label">Name</label>
                    <div class="col-sm-6">
                        <input id="txtName" asp-for="Name" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" asp-for="DateOfBirth">Date Of Birth : </label>
                    <div class="col-sm-4">
                        <div class='input-group date' id='BsDateTimePicker'>
                            <input placeholder="YYYY-MM-DD" class="form-control" asp-for="DateOfBirth" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Nric" class="col-sm-4 control-label">Nric</label>
                    <div class="col-sm-6">
                        <input id="txtName" asp-for="Nric" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="Nric" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3" asp-for="MedicalHistory">Medical History (Max: 200 words) : </label>
                    <div class="col-sm-5">
                        <input type="text" height="7" asp-for="MedicalHistory" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="MedicalHistory" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="AnnualIncome" class="col-sm-2 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="AnnualIncome" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3" asp-for="Address">Address : </label>
                    <div class="col-sm-5">
                        <input type="text" height="7" asp-for="Address" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="RelationshipToUser" class="col-sm-4 control-label">Relationship :</label>
                    <div class="col-sm-6">
                        <input id="txtName" asp-for="RelationshipToUser" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="RelationshipToUser" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Postalcode" class="col-sm-2 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Postalcode" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="col-sm-2 control-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Phone" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Gender" class="col-sm-2 control-label"></label>
                    <div class="col-sm-7">
                        <input type="radio" asp-for="Gender" value="M" checked="checked" /> M
                        <input type="radio" asp-for="Gender" value="F" /> F
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>